use_frameworks!


def example_pods
    pod 'SafeDataEntry', :path => '../'
end

target 'SafeDataEntry_Example' do
    example_pods
end

target 'SafeDataEntry_Tests' do
    example_pods
end

target 'SafeDataEntry_ExampleUITests' do
    example_pods
end

